#!/usr/bin/env python
from subprocess import Popen,PIPE
import os, sys
import time
import re, json


def check_proc():
    cmd = "ps aux | grep pi-sensor"
    proc=Popen(cmd, shell=True, stdout=PIPE)
    status_output = proc.communicate()[0]
    #print status_output
    search_str = '(.*)pi-sensor/daemon.*'
    m = re.search(search_str, status_output)
    if m == None:
        return False
    else:
        return True

if __name__ == '__main__':
    while True:
        if check_proc() == False:
            print "service not exist restart it"
            os.system('service pi-sensor restart')
        time.sleep(60)
